// Generated by CoffeeScript 1.3.3
(function() {
  var Router,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Router = (function(_super) {

    __extends(Router, _super);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.initialize = function() {
      return Backbone.history.start();
    };

    Router.prototype.routes = {
      "": "index",
      "destination": "destination",
      "route": "routeMap",
      "timeline": "timeline",
      "detail?id=:id": "detail",
      "information": "information",
      "category?id=:id": "category",
      "error?reason=:reason": "error"
    };

    Router.prototype.index = function() {
      if ($.mobile.activePage.attr("id") === "empty-page") {
        return this.destination();
      }
    };

    Router.prototype.destination = function() {
      return require(["views/destination"], function() {
        views.destination.render();
        return $.mobile.changePage($("#destination"), {
          changeHash: true
        });
      });
    };

    Router.prototype.routeMap = function() {
      return require(["views/route-map"], function() {
        views.routeMap.render();
        return $.mobile.changePage($("#route"), {
          changeHash: false
        });
      });
    };

    Router.prototype.timeline = function() {
      return require(["views/timeline"], function() {
        views.timeline.render();
        return $.mobile.changePage($("#timeline"), {
          changeHash: false
        });
      });
    };

    Router.prototype.detail = function(id) {
      return require(["views/detail"], function() {
        views.detail.render(id);
        return $.mobile.changePage($("#detail"), {
          changeHash: false
        });
      });
    };

    Router.prototype.information = function() {
      return require(["views/information"], function() {
        views.information.render();
        return $.mobile.changePage($("#information"), {
          changeHash: false
        });
      });
    };

    Router.prototype.error = function(reason) {
      return require(["views/error"], function() {
        views.error.render(reason);
        return $.mobile.changePage($("#error"), {
          changeHash: false
        });
      });
    };

    return Router;

  })(Backbone.Router);

  utils.app = new Router;

}).call(this);
