// Generated by CoffeeScript 1.3.3
(function() {

  define(["models/map", "views/map", "text!templates/detail.html", "models/route", "models/location", "collections/locations", "views/header"], function(Map, MapView, Template, Route, Location, Locations) {
    return views.detail = new (MapView.extend({
      el: "#detail",
      template: _.template(Template),
      events: {
        "tap .category-filter": "categories"
      },
      mapElement: "detail-map",
      render: function(id) {
        if (id === "undefined") {
          return;
        }
        if (utils.route === null || utils.locations === null) {
          utils.initFail();
          return;
        }
        views.header.render(this.el);
        this.poi = new Locations(utils.locations.getById(id)).models[0].toJSON();
        $("#" + this.el.id + " div[data-role='content']").html(this.template({
          location: this.poi
        }));
        this.updateMap();
        this.clearRoute();
        this.clearPOILayer();
        this.renderRoute();
        return this.renderPoi();
      },
      categories: function(e) {
        return utils.setCategory(e);
      },
      renderPoi: function() {
        var poiFeature, position;
        position = utils.transformLonLat(this.poi.lon, this.poi.lat);
        poiFeature = new OpenLayers.Feature.Vector(new OpenLayers.Geometry.Point(position.lon, position.lat));
        poiFeature.attributes = this.poi;
        this.poiLayer.addFeatures([poiFeature]);
        return utils.detailMap.instance.setCenter(position, 14);
      }
    }));
  });

}).call(this);
