// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["text!templates/error.html", "views/header"], function(Template) {
    var Error;
    Error = (function(_super) {

      __extends(Error, _super);

      function Error() {
        return Error.__super__.constructor.apply(this, arguments);
      }

      Error.prototype.el = "#error";

      Error.prototype.template = _.template(Template);

      Error.prototype.events = {
        "tap .category-filter": "categories"
      };

      Error.prototype.render = function(reason) {
        views.header.render(this.el);
        return $("#" + this.el.id + " div[data-role='content']").html(this.template({
          reason: reason
        }));
      };

      Error.prototype.categories = function(e) {
        return utils.setCategory(e);
      };

      return Error;

    })(Backbone.View);
    return views.error = new Error;
  });

}).call(this);
