// Generated by CoffeeScript 1.3.3
(function() {

  define(["models/map", "views/map", "models/location", "collections/locations", "models/route", "views/header"], function(Map, MapView, Location, Locations, Route) {
    return views.routeMap = new (MapView.extend({
      el: "#route",
      render: function(type) {
        if (utils.route === null || utils.locations === null) {
          utils.initFail();
          return;
        }
        if (type !== "poi") {
          views.header.render(this.el);
        }
        this.updateMap();
        this.clearRoute();
        this.clearPOILayer();
        this.addStartAndEndPoints();
        this.renderRoute(true);
        return this.renderPois();
      },
      renderPois: function() {
        var pois,
          _this = this;
        pois = new Locations(utils.locations.filterOutCategories());
        return pois.each(function(poi) {
          var poiFeature, position;
          position = utils.transformLonLat(poi.attributes.lon, poi.attributes.lat);
          poiFeature = new OpenLayers.Feature.Vector(new OpenLayers.Geometry.Point(position.lon, position.lat));
          poiFeature.attributes = poi.attributes;
          return _this.poiLayer.addFeatures([poiFeature]);
        });
      },
      addStartAndEndPoints: function() {
        var endPointFeature, position, route, startPointFeature;
        route = utils.route.attributes.routes[0].overview_path;
        position = utils.transformLonLat(route[0].Za, route[0].Ya);
        startPointFeature = new OpenLayers.Feature.Vector(new OpenLayers.Geometry.Point(position.lon, position.lat));
        startPointFeature.attributes = {
          type: "start-point"
        };
        this.poiLayer.addFeatures([startPointFeature]);
        position = utils.transformLonLat(route.slice(-1)[0].Za, route.slice(-1)[0].Ya);
        endPointFeature = new OpenLayers.Feature.Vector(new OpenLayers.Geometry.Point(position.lon, position.lat));
        endPointFeature.attributes = {
          type: "end-point"
        };
        return this.poiLayer.addFeatures([endPointFeature]);
      }
    }));
  });

}).call(this);
