// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["text!templates/timeline.html", "models/route", "models/location", "collections/locations", "views/header"], function(Template, Route, Location, Locations) {
    var Timeline;
    Timeline = (function(_super) {

      __extends(Timeline, _super);

      function Timeline() {
        return Timeline.__super__.constructor.apply(this, arguments);
      }

      Timeline.prototype.el = "#timeline";

      Timeline.prototype.template = _.template(Template);

      Timeline.prototype.events = {
        "tap .category-filter": "categories"
      };

      Timeline.prototype.render = function(type) {
        var locations;
        if (utils.route === null || utils.locations === null) {
          utils.initFail();
          return;
        }
        if (type !== "poi") {
          views.header.render(this.el);
        }
        locations = new Locations(utils.locations.filterOutCategories());
        locations = new Locations(locations.sortByDistance());
        return $("#" + this.el.id + " div[data-role='content']").html(this.template({
          locations: locations.toJSON()
        }));
      };

      Timeline.prototype.categories = function(e) {
        utils.setCategory(e);
        return this.render("poi");
      };

      return Timeline;

    })(Backbone.View);
    return views.timeline = new Timeline;
  });

}).call(this);
