// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define([], function() {
    var Route;
    return Route = (function(_super) {

      __extends(Route, _super);

      function Route() {
        return Route.__super__.constructor.apply(this, arguments);
      }

      Route.prototype.id = "route";

      Route.prototype.initialize = function() {};

      Route.prototype.setAverageSpeed = function() {
        return this.set({
          averageSpeed: this.get("routes")[0].legs[0].distance.value / this.get("routes")[0].legs[0].duration.value
        });
      };

      Route.prototype.fetch = function(options) {
        var data, json;
        json = localStorage.getItem(this.id);
        if (json) {
          data = JSON.parse(json);
          return this.set(data);
        }
      };

      Route.prototype.save = function(attributes, options) {
        return localStorage.setItem(this.id, JSON.stringify(this.attributes));
      };

      Route.prototype.destroy = function() {
        return localStorage.removeItem(this.id);
      };

      return Route;

    })(Backbone.Model);
  });

}).call(this);
